# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ly-do-not-delete-cn-beijing-pre.cr.volces.com/test/nginx:ffo
        ports:
        - containerPort: 80
